version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    profiles: [main, storage]
    ports:
      - "5433:5432"
    volumes:
      - ./db/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./db/function_procedure.sql:/docker-entrypoint-initdb.d/function_procedure.sql
      - ./db/index.sql:/docker-entrypoint-initdb.d/index.sql
      - ./db/trigger.sql:/docker-entrypoint-initdb.d/trigger.sql
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    profiles: [main]
    depends_on:
      - db
    network_mode: host
    env_file: ".env"

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    profiles: [sonarqube]
    ports:
      - "9000:9000"
    env_file: "sonarqube.env"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  sonarqube-db:
    image: postgres:15-alpine
    container_name: sonar_db
    profiles: [sonarqube]
    env_file: "sonarqube.env"
    volumes:
      - sonar_db_data:/var/lib/postgresql/data

  sonarqube-check-app:
    build:
      dockerfile: sonarqube.Dockerfile
    profiles: [sonarqube]
    depends_on:
      - sonarqube
    network_mode: host
    env_file: "sonarqube.env"

volumes:
  pgdata:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonar_db_data:
