# ?????? ????????????????? ???????????
testcontainers.reuse.enable=true

# ??????? Ryuk (?? ???????? ???????? ? Named Pipe)
testcontainers.ryuk.disabled=true

# ??????? ????????
testcontainers.startup.timeout=300